--- #YAML:1.0
name:               CSS-Flip
version:            0.03
abstract:           Flip direction of Cascading Style Sheet (CSS)
author:
    - Hatuka*nezumi - IKEDA Soji <hatuka@nezumi.nu>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.46
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0.45
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://repos.nezumi.nu/repos/CSS-Flip/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
